### ISSUE TITLE
Support for Partial Indexes

### ISSUE THREAD

**Issue by JPDSousa** [JPDSousa/mongo-obj-framework#23]
Description
----
[Partial indexes](https://docs.mongodb.com/manual/core/index-partial/) allow users to filter documents that are added to the index.

Use Cases
-----
- Avoid `NULL` values to be indexed, since MongoDB only allow one `NULL` value in unique indexes ([source](https://docs.mongodb.com/manual/core/index-unique/#unique-index-and-missing-field)).

**Comment by yashdeeph709** [comment]
Hi JPD,

I was trying to code the support for partial indexes in mongo-obj-framework.
I am having some trouble in code how to make the partial index querying annotations correct.
Can you look at my code and suggest something.
Fork      :  https://github.com/XoriantOpenSource/mongo-obj-framework.git 
Branch  :  SmofPartialIndex

**Comment by JPDSousa** [comment]
I'm analyzing your code. I like how you're handling the problem, but i have a question: why not follow the mongoDB syntax?
```
db.restaurants.createIndex(
   { cuisine: 1, name: 1 },
   { partialFilterExpression: { rating: { $gt: 5 } } }
)
```
They simply add a new field with the partial index information. My original idea was to extend the [SmofIndex](https://github.com/JPDSousa/mongo-obj-framework/blob/master/src/main/java/org/smof/annnotations/SmofIndex.java) with the additional PartialIndex field (probably a new annotation, just like you did).

**Comment by yashdeeph709** [comment]
I am unable to find how to provide a default for pfe so that if there is no pfe user don't need to do anything for that.
https://github.com/XoriantOpenSource/mongo-obj-framework/blob/SmofPartialIndex/src/org/smof/annnotations/SmofPartialIndex.java#L17

**Comment by yashdeeph709** [comment]
hi JPD,
I have done the Partial Index implementation as we needed. I can enhance it more if you create some more tickets for unit tests and documentation and can we complete it by today. I want to submit this pull request to hacktoberfest.

**Comment by JPDSousa** [comment]
I'll check this tomorrow when i have more time. There are some issues that i would like to discuss with you, but for now let me just thank you for the amazing work and dedication on this issue. And do not worry about Hacktoberfest, as they only count for openned pull requests (thus i don't need to accept this right away).

**Comment by yashdeeph709** [comment]
Hi JP,
I have improved the pr as per you suggested. The new structure seems kinda cool. :-)
