### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by JPDSousa** [JPDSousa/mongo-obj-framework#49]
Hacktoberfester? :octocat:
------------
Hey Hacktoberfester, if you came across this issue and you like MongoDB (and java), you've just found an awesome project to contribute to!

If you're not so much into databases and ORMs but you would like to contribute to other projects of mine: [search my other Hacktoberfest issues](https://github.com/search?utf8=%E2%9C%93&q=label%3Ahacktoberfest+state%3Aopen+type%3Aissue+author%3AJPDSousa&type=)

Description 🔍 
------------
This is actually a simple issue, easily achievable. Just go to the [version eye page](https://www.versioneye.com/user/projects/5933e3e776149d00503a8c25) (or click the version eye badge in the README file), where dependency versions are managed, see which dependencies are outdated  and update the pom.xml file with the newest versions.

**Note** that some dependencies are muted, as they most likely require additional code updates. Feel free to try to update them as well!

**Comment by andreblanke** [comment]
I'd like to work on this issue.
I suppose migrating from JUnit 4 to 5 is not necessary at the moment?

**Comment by JPDSousa** [comment]
Not necessarily @andreblanke , but can be done if you wish to contribute that way!
