### ISSUE TITLE
Change project structure to maven hierarchy

### ISSUE THREAD

**Issue by Nipel-Crumple** [JPDSousa/mongo-obj-framework#58]
@JPDSousa hi!

What do you think of creating maven hierarchy for this project? It will help to handle resources/testResources automatically by maven. If yes, then I'm ready to change the structure, feel free to assign me to this issue 🙂 

Thanks a lot!

**Comment by JPDSousa** [comment]
Hi @Nipel-Crumple ! In fact, i should have done this already, but i never got the time. So, basically yes, feel free to update the project hierarchy, just make sure you make it fast (as in the time between the push and the pull request) to avoid merging conflicts 😉

**Comment by Nipel-Crumple** [comment]
Changed project structure, review all changes, please
