### ISSUE TITLE
VersionEye Link on Readme.md is broken

### ISSUE THREAD

**Issue by yashdeeph709** [JPDSousa/mongo-obj-framework#80]
![image](https://user-images.githubusercontent.com/6427291/32389639-58d14edc-c0f1-11e7-8ce1-7466a15ad2d2.png)

**Comment by JPDSousa** [comment]
Its fine on my end. Try refresh it.

Actually, version eye will become deprecated in a few months ([source](https://blog.versioneye.com/)), and when it does, i'll probably remove it from the badges section.

Anyway, @yashdeeph709  just confirm me if the badge is working on your end so i can close the issue.
